name: Validate Generated Go

on:
    push:
        paths:
            - .github/workflows/**
            - gen/go/**

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.26
            - working-directory: gen/go
              run: go list
            - working-directory: gen/go
              run: go vet
